#pragma once
/**
 * @file sqlite3.hpp
 * @date 29/06/2026
 * @authors
 * 		- CRESP Enguerran
 * @brief A try of representing the way sqlite3 works in python, using the C lib <sqlite3.h>
 * 
 * @ai This file was almost entirely generated by AI to save time on a small componenet, but verified and
 *     optimized by a human. The idea was human, the execution made by AI and the debugging was both 
 *     (because of vectors shenanigans).
 * 
 * Comments and Documentation are here to help the developers who come after.
 */
#include <iostream>
#include <sqlite3.h>
#include <string>
#include <vector>
#include <memory>
#include <variant>
#include <utility>
#include <concepts>
#include <nlohmann/json.hpp>

#define GET_SQLITE3_VALUE(type,var) (*std::get_if<type>(&var))

using RowValue = std::variant<std::monostate, int, double, std::string>;
using Row = std::vector<RowValue>;
struct SQLtoJSONlist;
struct SQLtoJSONobject;

std::ostream& operator<<(std::ostream&, const RowValue&);
std::ostream& operator<<(std::ostream&, const Row&);
std::ostream& operator<<(std::ostream&, const std::vector<Row>&);
nlohmann::json& operator<<(nlohmann::json&, const SQLtoJSONlist&);
nlohmann::json& operator<<(nlohmann::json&, const SQLtoJSONobject&);

using null = std::monostate;

namespace SQLite3 {

class Cursor {
private:
	std::shared_ptr<sqlite3> db; 
	bool autoCommit = true;
	sqlite3_stmt* stmt = nullptr;

	/**
     * @fn bind_param
     * @param index The position in all of the '?' presents in the query
     * @tparam value Enum Any enum or enum class
     */
    template<typename Enum>
    requires std::is_enum_v<Enum>
    void bind_param(int index, Enum value) {
        // std::underlying_type_t récupère automatiquement int, uint8_t, etc.
        using UnderlyingType = std::underlying_type_t<Enum>;
        this->bind_param(index, static_cast<UnderlyingType>(value));
    }

	/**
	 * @fn bind_param
	 * @param index The position in all of the '?' presents in the query
	 * @tparam value Integral value only accepted
	 */
	template<std::integral Integral>
	void bind_param(int index, Integral value) { 
		sqlite3_bind_int64(this->stmt, index, static_cast<long long>(value)); 
	}

	/**
	 * @fn bind_param
	 * @param index The position in all of the '?' presents in the query
	 * @tparam value Floating point value only accepted
	 */
	template<std::floating_point Floating>
	void bind_param(int index, Floating value) { 
		sqlite3_bind_double(this->stmt, index, static_cast<double>(value)); 
	}

	/**
	 * @fn bind_param
	 * @param index The position in all of the '?' presents in the query
	 * @param value The string element, passed in with the c_str() method
	 */
	void bind_param(int index, const std::string& value) { 
		sqlite3_bind_text(this->stmt, index, value.c_str(), -1, SQLITE_TRANSIENT); 
	}

	/**
	 * @fn bind_param
	 * @param index The position in all of the '?' presents in the query
	 * @param value The string element, passing natively into the method body
	 */
	void bind_param(int index, const char* value) { 
		sqlite3_bind_text(this->stmt, index, value, -1, SQLITE_TRANSIENT); 
	}

	/**
	 * @fn bind_param
	 * @param index The position in all of the '?' presents in the query
	 * @param std::monostate The monostate element, passed in with the monostate{} method
	 */
	void bind_param(int index, std::monostate) {
		sqlite3_bind_null(this->stmt, index);
	}

	/**
	 * @fn bind_all
	 * @tparam args variadic rvalues for perfect forwarding
	 */
	template <typename... Args>
	void bind_all(Args&&... args) {
		int index = 1;
		(bind_param(index++, std::forward<Args>(args)), ...);
	}

public:
	Cursor(std::shared_ptr<sqlite3> db_connection, bool autoCommit) 
	: db(db_connection), autoCommit(autoCommit), stmt(nullptr) {}

	Cursor(const Cursor&) = delete;
	Cursor& operator=(const Cursor&) = delete;
	Cursor() = delete;
	Cursor(Cursor&&) = delete;
	Cursor& operator=(Cursor&&) = delete;

	~Cursor() {
		this->close();
	}

	/**
	 * @fn close
	 * @brief flushes the last query and restart the sqlite query state
	 */
	void close() {
		if (this->stmt) {
			sqlite3_finalize(this->stmt);
			stmt = nullptr;
		}
	}

	/**
	 * @fn autoBegin
	 * @brief Automatically begin a transaction when @p autoCommit is set to @a true
	 */
	void autoBegin() {
		char* err = nullptr;
		if (sqlite3_exec(db.get(), "BEGIN TRANSACTION;", nullptr, nullptr, &err) != SQLITE_OK) {
			std::string msg(err);
			sqlite3_free(err);
			throw std::runtime_error("Erreur d'initialisation de la transaction : " + msg);
		}
	}

	/**
	 * @fn isWriteQuery
	 * @param sql the entire query checking and trim the start of the query
	 * @returns @a true if the query start by INSERT, UPDATE or DELETE. @a false otherwise
	 */
	inline bool isWriteQuery(std::string sql) {
		sql.erase(0, sql.find_first_not_of(" \t\n\r"));
		if (sql.empty()) return false;

		std::string prefix = sql.substr(0, 6);
		for (char &c : prefix) c = std::toupper(c);
		
		return ( prefix == "INSERT" || prefix == "UPDATE" || prefix == "DELETE" || prefix == "CREATE" );
	}

	/**
	 * @fn execute
	 * @param sql The query body
	 * @tparam args the variadic arguments of the body (like the tuple used in the same python method)
	 * @returns the class used, useful for forwarding with a ->fetchone(), ->fetchmany() or ->fetchall()
	 */
	template <typename... Args>
	Cursor* execute(const std::string sql, Args&&... args) {
		this->close(); // Cleans from previous request

		if(!this->autoCommit && this->isWriteQuery(sql))
			this->autoBegin();

		if (sqlite3_prepare_v2(this->db.get(), sql.c_str(), -1, &(this->stmt), nullptr) != SQLITE_OK) {
			throw std::runtime_error("Erreur de préparation : " + std::string(sqlite3_errmsg(this->db.get())));
		}

		if constexpr (sizeof...(Args) > 0) {
			this->bind_all(std::forward<Args>(args)...);
		}

		// Auto-add if the request started by an INSERT, UPDATE or DELETE
		if (this->isWriteQuery(sql)) {
			int rc = sqlite3_step(this->stmt);
			if (rc != SQLITE_DONE) {
				throw std::runtime_error("Erreur d'exécution de l'écriture : " + std::string(sqlite3_errmsg(this->db.get())));
			}
		}

		return this;
	}

	/**
	 * @fn fetchone
	 * @brief Fetches the first row or the result, event if more rows exists.
	 * @returns A row fetched by a previous query or nothing is the query dosen't result in anything (!= SQLITE_ROW)
	 */
	Row fetchone() {
		if (!this->stmt) return {};

		int rc = sqlite3_step(this->stmt);
		if (rc == SQLITE_ROW) {
			Row row;
			int col_count = sqlite3_column_count(this->stmt);
			for (int i = 0; i < col_count; ++i) {
				int type = sqlite3_column_type(this->stmt, i);

				if(type == SQLITE_NULL) {
					row.push_back(std::monostate{});
				} else if (type == SQLITE_INTEGER) {
					row.push_back(sqlite3_column_int(this->stmt, i));
				} else if (type == SQLITE_FLOAT) {
					row.push_back(sqlite3_column_double(this->stmt, i));
				} else {
					row.push_back(std::string(reinterpret_cast<const char*>(sqlite3_column_text(this->stmt, i))));
				}
			}
			return row;
		}
		return {}; // No results dumbass
	}

	/**
	 * @fn fetchall
	 * @brief Returns all rows possible from a query proviously executed
	 * @returns a matrix of the query previously excuted
	 */
	std::vector<Row> fetchall() {
		std::vector<Row> results;
		while (true) {
			Row row = this->fetchone();
			if (row.empty()) break;
			results.push_back(row);
		}
		return results;
	}

	/**
	 * @fn fetchmany
	 * @param nbOfLines Number of lines wanted for extraction or less
	 * @returns A matrix of the query previously executed, the length of the query is equal or inferior of @p nbOfLines
	 */
	std::vector<Row> fetchmany(int nbOfLines) {
		std::vector<Row> results;
		for (int i = 0; i < nbOfLines; i++) {
			Row row = this->fetchone();
			if (row.empty()) break;
			results.push_back(row);
		}
		return results;
	}

	/**
	* @fn getColumns
	* @brief Get the Columns object
	* @return A list of all the column names from the last query
	*/
	std::vector<std::string> getColumns() {
		if(!this->stmt) return {};
		std::vector<std::string> cols;

		int colCount = sqlite3_column_count(this->stmt);
		for (int i = 0; i < colCount; i++)
		{
			cols.push_back(sqlite3_column_name(this->stmt,i));
		}
		
		return cols;
	}
};

class Connection {
private:
	std::shared_ptr<sqlite3> db;
	bool autocommit = true;

public:
	Connection(const std::string& db_name, bool autoCommit = true, bool foreignKeysEnforcment = true) {
		sqlite3* raw_db = nullptr;
		if (sqlite3_open(db_name.c_str(), &raw_db) != SQLITE_OK) {
			if (raw_db) sqlite3_close(raw_db);
			throw std::runtime_error("Impossible d'ouvrir la BDD");
		}
		// Custom destrucor for shared pointer
		this->db = std::shared_ptr<sqlite3>(raw_db, [](sqlite3* d) {
			sqlite3_close(d);
			std::cout << "[BDD Fermée proprement]\n";
		});
		this->autocommit = autoCommit;
		
		if(foreignKeysEnforcment) {
			sqlite3_exec(this->db.get(),"PRAGMA foreign_keys = ON;", nullptr, nullptr, nullptr);
		}
	}

	/**
	 * @fn cursor
	 * @brief An exclusive factory for query execution.
	 * @returns A @c Cursor object
	 */
	Cursor cursor() {
		return Cursor(this->db,this->autocommit);
	}

	/**
	 * @fn commit
	 * @brief Needs to be used if @p autoCommit is set to @a false
	 */
	void commit() {
		char* err = nullptr;
		if (sqlite3_exec(this->db.get(), "COMMIT;", nullptr, nullptr, &err) != SQLITE_OK) {
			std::string msg(err);
			sqlite3_free(err);
			throw std::runtime_error("Commit échoué : " + msg);
		}
	}

	/**
	 * @fn rollback
	 * @brief Needs to be used if @p autoCommit is set to @a false
	 */
	void rollback() {
		sqlite3_exec(this->db.get(), "ROLLBACK;", nullptr, nullptr, nullptr);
	}

	/**
	 * @fn last_insert_rowid
	 * @brief Gets the last insert row id
	 * @returns The last row id inserted
	 */
	inline long long last_insert_rowid() const noexcept {
		return sqlite3_last_insert_rowid(this->db.get());
	}
};
}

// equivalents to .__str__() in python, prints out the entire query

/**
 * @fn operator<<
 * @param os The output stream used to print text
 * @param query The executed query formatted
 * @returns A correctly formated, Python-style of the list of tuples.
 */
inline std::ostream& operator<<(std::ostream& os, const std::vector<Row>& query) {
	os << '[';
	for (size_t i = 0; i < query.size(); ++i) {
		os << query[i] << ',';
		if (i < query.size() - 1) {
			os << "\n "; // A newline only if another value is after
		}
	}
	return os << ']';
}

/**
 * @fn operator<<
 * @param os The output stream used to print text
 * @param row A row of queried values
 * @returns A correctly formatted row of data pulled from the query previously executed.
 */
inline std::ostream& operator<<(std::ostream& os, const Row& row) {
	os << '(';
	for (size_t i = 0; i < row.size(); ++i) {
		os << row[i];
		if (i < row.size() - 1) {
			os << ", "; // A comma only if another value is after
		}
	}
	return os << ')';
}

/**
 * @fn operator<<
 * @param os The output stream used to print text
 * @param rval A queried value
 * @returns A correctly formatted data pulled from the query previously executed.
 */
inline std::ostream& operator<<(std::ostream& os, const RowValue& rval) {
	std::visit([&os](const auto& val) {
		using T = std::decay_t<decltype(val)>;
		if constexpr (std::is_same_v<T,std::monostate>) {
			os << "null";
		} else {
            os << val;
        }
	}, rval);
	return os;
}

struct SQLtoJSONlist {
	std::vector<std::string> columns;
	std::vector<Row> rows;
};

struct SQLtoJSONobject {
	std::vector<std::string> columns;
	Row row;
};

inline nlohmann::json& operator<<(nlohmann::json& j, const SQLtoJSONlist& result) {
	j = nlohmann::json::array(); // [ ]

	for (const auto& row : result.rows) {
		nlohmann::json json_obj = nlohmann::json::object(); // { }
		for (size_t i = 0; i < row.size(); ++i) {
			std::visit([&json_obj, &result, i](const auto& val) {
				// On utilise le nom de la colonne comme clef JSON
				using T = std::decay_t<decltype(val)>;
				if constexpr (std::is_same_v<T, std::monostate>) {
					// En JSON, un NULL SQL devient un vrai 'null' valide
					json_obj[result.columns[i]] = nullptr; 
				} else {
					json_obj[result.columns[i]] = val;
				}
			}, row[i]);
		}
		j.push_back(json_obj);
	}
	return j;
}

inline nlohmann::json& operator<<(nlohmann::json& j, const SQLtoJSONobject& result) {
	j = nlohmann::json::object(); // { }
		for (size_t i = 0; i < result.row.size(); ++i) {
			std::visit([&j, &result, i](const auto& val) {
				// On utilise le nom de la colonne comme clef JSON
				using T = std::decay_t<decltype(val)>;
				if constexpr (std::is_same_v<T, std::monostate>) {
					// En JSON, un NULL SQL devient un vrai 'null' valide
					j[result.columns[i]] = nullptr; 
				} else {
					j[result.columns[i]] = val;
				}
			}, result.row[i]);
		}
	return j;
}
